ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_5';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_6';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_7';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_8';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_9';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEAR_10';
