-- Add BANK_TRANSFER to the PaymentMethodType enum.
-- MySQL requires re-stating the full ENUM set to add a value.

ALTER TABLE `Transaction`
  MODIFY COLUMN `method` ENUM('CREDIT_CARD','PAYPAL','SEPA','CRYPTO','ACCOUNT_BALANCE','BANK_TRANSFER') NOT NULL;

ALTER TABLE `PaymentMethod`
  MODIFY COLUMN `type` ENUM('CREDIT_CARD','PAYPAL','SEPA','CRYPTO','ACCOUNT_BALANCE','BANK_TRANSFER') NOT NULL;

ALTER TABLE `Invoice`
  MODIFY COLUMN `paymentMethod` ENUM('CREDIT_CARD','PAYPAL','SEPA','CRYPTO','ACCOUNT_BALANCE','BANK_TRANSFER') NULL;

ALTER TABLE `PaymentProcessorConfig`
  MODIFY COLUMN `method` ENUM('CREDIT_CARD','PAYPAL','SEPA','CRYPTO','ACCOUNT_BALANCE','BANK_TRANSFER') NOT NULL;
