import { getLocale } from "../../../../lib/i18n";
import styles from "../legal.module.css";

export default async function ZahlungPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  const locale = getLocale(rawLocale);
  const isDe = locale === "de";

  return (
    <>
      <section className={styles.hero}>
        <div className="container">
          <span className="eyebrow">{isDe ? "Rechtliches" : "Legal"}</span>
          <h1>{isDe ? "Zahlungsinformationen" : "Payment Information"}</h1>
        </div>
      </section>

      <section className={styles.content}>
        <div className="container">
          <div className={styles.prose}>
            <p>
              {isDe
                ? "Auf dieser Seite finden Sie alle wichtigen Informationen zu unseren Zahlungsarten, Abrechnungen und Rückerstattungen."
                : "On this page you will find all important information about our payment methods, billing and refunds."}
            </p>

            <h2>{isDe ? "Verfügbare Zahlungsarten" : "Available payment methods"}</h2>
            <p>{isDe ? "Wir bieten Ihnen folgende sichere Zahlungsmethoden an:" : "We offer you the following secure payment methods:"}</p>
            <ul>
              <li>PayPal</li>
              <li>Mollie ({isDe ? "mit den Optionen SEPA-Lastschrift, Kreditkarte und Banküberweisung" : "with the options SEPA direct debit, credit card and bank transfer"})</li>
            </ul>
            <p>
              {isDe
                ? "Nach Abschluss Ihrer Bestellung werden Sie automatisch auf die sichere Zahlungsseite des jeweiligen Zahlungsanbieters weitergeleitet. Ihre Zahlungsdaten werden dort ausschließlich von PayPal oder Mollie verarbeitet. Dezhost speichert keine Zahlungsinformationen."
                : "After completing your order, you will be automatically redirected to the secure payment page of the respective payment provider. Your payment data is processed there exclusively by PayPal or Mollie. Dezhost does not store payment information."}
            </p>

            <h2>{isDe ? "Zahlungszeitpunkt" : "Payment timing"}</h2>
            <p>
              {isDe
                ? "Die Zahlung erfolgt unmittelbar nach Abschluss der Bestellung. Sobald der Zahlungseingang bestätigt wurde, wird Ihr Auftrag automatisch aktiviert oder manuell freigeschaltet."
                : "Payment is made immediately after completing the order. Once payment receipt is confirmed, your order will be automatically activated or manually unlocked."}
            </p>

            <h2>{isDe ? "Rechnungsstellung" : "Invoicing"}</h2>
            <p>{isDe ? "Alle Rechnungen werden automatisch von unserem Abrechnungssystem erstellt und per E-Mail an Sie gesendet." : "All invoices are automatically generated by our billing system and sent to you by email."}</p>
            <ul>
              <li>{isDe ? "Unbezahlte Rechnungen werden mit dem Präfix UNPAID versehen." : "Unpaid invoices are marked with the prefix UNPAID."}</li>
              <li>{isDe ? "Bezahlte Rechnungen tragen das Präfix PAID und können für steuerliche Zwecke verwendet werden." : "Paid invoices carry the prefix PAID and can be used for tax purposes."}</li>
            </ul>
            <p>
              {isDe
                ? "Darüber hinaus können Sie alle Rechnungen jederzeit im Kundenbereich Mein Dezhost als PDF-Datei herunterladen."
                : "In addition, you can download all invoices at any time in the customer area My Dezhost as a PDF file."}
            </p>

            <h2>{isDe ? "Rückerstattungen" : "Refunds"}</h2>
            <ul>
              <li>{isDe ? "Für Hosting-Dienste gilt ein 14-tägiges Rückgaberecht." : "A 14-day right of return applies to hosting services."}</li>
              <li>{isDe ? "Domainregistrierungen sind von der Rückerstattung ausgeschlossen." : "Domain registrations are excluded from refunds."}</li>
            </ul>
            <p>
              {isDe
                ? "Details hierzu finden Sie in unserer Widerrufsbelehrung."
                : "Details can be found in our cancellation policy."}
            </p>

            <h2>{isDe ? "Währung & Steuern" : "Currency & taxes"}</h2>
            <p>
              {isDe
                ? "Alle Preise verstehen sich in Euro (EUR). Wir sind ein Kleinunternehmen gemäß § 19 UStG, daher erfolgt keine Ausweisung der Mehrwertsteuer auf unseren Rechnungen."
                : "All prices are in euros (EUR). We are a small business pursuant to § 19 UStG, therefore no VAT is shown on our invoices."}
            </p>

            <h2>{isDe ? "Gebühren & Zusatzkosten" : "Fees & additional costs"}</h2>
            <ul>
              <li>{isDe ? "Unsere Preise sind Endpreise." : "Our prices are final prices."}</li>
              <li>{isDe ? "Es fallen keine zusätzlichen oder versteckten Gebühren an." : "There are no additional or hidden fees."}</li>
              <li>{isDe ? "Eventuelle Kosten der Zahlungsanbieter (z. B. PayPal oder Mollie) werden vollständig von uns getragen." : "Any costs of payment providers (e.g. PayPal or Mollie) are fully borne by us."}</li>
            </ul>

            <h2>{isDe ? "Fragen zur Zahlung" : "Questions about payment"}</h2>
            <p>
              {isDe
                ? "Bei Fragen zur Zahlung oder Rechnungsstellung wenden Sie sich bitte an:"
                : "For questions about payment or invoicing, please contact:"}
              <br />
              📧 <a href="mailto:support@dezhost.com">support@dezhost.com</a>
              <br />
              {isDe ? "Wir helfen Ihnen gerne weiter." : "We are happy to help."}
            </p>

            <span className={styles.updated}>{isDe ? "Stand: November 2025" : "As of: November 2025"}</span>
          </div>
        </div>
      </section>
    </>
  );
}
