import net from "node:net";
import tls from "node:tls";

export type ImapMailboxConfig = {
  address: string;
  // Department slug this mailbox maps to (e.g. "sales", "support").
  department: string;
  enabled?: boolean;
  host?: string;
  mailbox?: string;
  password?: string;
  port?: number;
  secure?: boolean;
  username?: string;
};

export type ImapMessage = {
  body: string;
  from?: string;
  headers: Record<string, string>;
  subject: string;
  to?: string;
  uid: string;
};

export async function fetchUnreadImapMessages(config: ImapMailboxConfig) {
  if (!config.enabled || !config.host || !config.username || !config.password) {
    return [];
  }
  const socket = await connectImap(config);
  const client = imapClient(socket);
  try {
    await client.readGreeting();
    await client.command(`LOGIN ${quote(config.username)} ${quote(config.password)}`);
    await client.command(`SELECT ${quote(config.mailbox || "INBOX")}`);
    const search = await client.command("UID SEARCH UNSEEN");
    const uids = search.match(/\* SEARCH ([^\r\n]*)/)?.[1]?.trim().split(/\s+/).filter(Boolean) ?? [];
    const messages: ImapMessage[] = [];
    for (const uid of uids) {
      const raw = await client.command(`UID FETCH ${uid} BODY.PEEK[]`);
      const message = parseMessageLiteral(raw);
      if (!message) {
        continue;
      }
      messages.push({ ...parseRfc822(message), uid });
      await client.command(`UID STORE ${uid} +FLAGS.SILENT (\\Seen)`).catch(() => undefined);
    }
    return messages;
  } finally {
    await client.command("LOGOUT").catch(() => undefined);
    socket.end();
  }
}

function connectImap(config: ImapMailboxConfig) {
  const port = Number(config.port || 993);
  const host = config.host ?? "127.0.0.1";
  return new Promise<net.Socket>((resolve, reject) => {
    const socket = config.secure === false
      ? net.connect({ host, port })
      : tls.connect({ host, port, rejectUnauthorized: false });
    const timer = setTimeout(() => {
      socket.destroy();
      reject(new Error("IMAP connection timed out"));
    }, 10_000);
    socket.once("connect", () => {
      clearTimeout(timer);
      socket.setTimeout(10_000);
      socket.once("timeout", () => socket.destroy(new Error("IMAP response timed out")));
      resolve(socket);
    });
    socket.once("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });
  });
}

function imapClient(socket: net.Socket) {
  let tagCounter = 1;
  let buffer = "";
  socket.setEncoding("utf8");
  socket.on("data", (chunk) => {
    buffer += chunk;
  });

  return {
    readGreeting() {
      return waitFor(() => /^\* OK/m.test(buffer), () => buffer);
    },
    async command(command: string) {
      const tag = `A${String(tagCounter++).padStart(4, "0")}`;
      buffer = "";
      socket.write(`${tag} ${command}\r\n`);
      const response = await waitFor(() => new RegExp(`^${tag} (OK|NO|BAD)`, "m").test(buffer), () => buffer);
      if (new RegExp(`^${tag} (NO|BAD)`, "m").test(response)) {
        throw new Error(`IMAP command failed: ${response.split(/\r?\n/).at(-2) ?? command}`);
      }
      return response;
    }
  };
}

function waitFor(done: () => boolean, value: () => string) {
  return new Promise<string>((resolve, reject) => {
    const started = Date.now();
    const timer = setInterval(() => {
      if (done()) {
        clearInterval(timer);
        resolve(value());
        return;
      }
      if (Date.now() - started > 10_000) {
        clearInterval(timer);
        reject(new Error("IMAP response timed out"));
      }
    }, 20);
  });
}

function parseMessageLiteral(raw: string) {
  const match = raw.match(/\{(\d+)\}\r?\n/);
  if (!match?.[1] || match.index === undefined) {
    return undefined;
  }
  const start = match.index + match[0].length;
  return raw.slice(start, start + Number(match[1]));
}

// Exported for tests: full RFC 822 → { text body, headers, from/subject/to }.
export function parseRfc822(raw: string) {
  const { headers, body } = splitHeadersAndBody(raw);
  return {
    body: extractTextBody(headers, body),
    from: emailAddress(headers.from),
    headers,
    subject: decodeMimeWords(headers.subject ?? "Email ticket"),
    to: headers.to
  };
}

// RFC 3834 (+ de-facto headers): true when the message is machine-generated — auto-replies,
// delivery reports, mailing lists, our own notification mail — and must never open a ticket
// (that is how "ticket opened" notifications used to loop back in as new tickets).
export function isAutoGeneratedEmail(headers: Record<string, string>) {
  const autoSubmitted = (headers["auto-submitted"] ?? "").toLowerCase();
  if (autoSubmitted && autoSubmitted !== "no") {
    return true;
  }
  if (headers["x-auto-response-suppress"] || headers["x-autoreply"] || headers["x-autorespond"]) {
    return true;
  }
  const precedence = (headers.precedence ?? "").toLowerCase();
  if (["bulk", "junk", "auto_reply", "list"].includes(precedence)) {
    return true;
  }
  if ((headers["content-type"] ?? "").toLowerCase().includes("multipart/report")) {
    return true; // bounce/delivery status notifications
  }
  return /mailer-daemon|postmaster/i.test(headers.from ?? "");
}

function splitHeadersAndBody(raw: string) {
  const separator = raw.match(/\r?\n\r?\n/);
  const headerBlock = separator?.index !== undefined ? raw.slice(0, separator.index) : raw;
  const body = separator?.index !== undefined ? raw.slice(separator.index + separator[0].length) : "";
  return { body, headers: parseHeaders(headerBlock) };
}

function parseHeaders(value: string) {
  const lines = value.replace(/\r?\n[ \t]+/g, " ").split(/\r?\n/);
  const headers: Record<string, string> = {};
  for (const line of lines) {
    const index = line.indexOf(":");
    if (index <= 0) {
      continue;
    }
    headers[line.slice(0, index).toLowerCase()] = line.slice(index + 1).trim();
  }
  return headers;
}

// Tickets store PLAIN TEXT. Walk the MIME tree preferring the text/plain alternative and
// falling back to a tag-stripped text/html part — never the raw multipart source (which used
// to land as visible HTML/boundary noise inside the ticket body).
function extractTextBody(headers: Record<string, string>, body: string): string {
  const part = findTextPart(headers, body);
  if (!part) {
    return cleanupText(decodeTransferEncoding(headers, body));
  }
  const text = decodeTransferEncoding(part.headers, part.body);
  return cleanupText(part.type === "text/html" ? htmlToText(text) : text);
}

type MimeTextPart = { body: string; headers: Record<string, string>; type: "text/html" | "text/plain" };

function findTextPart(headers: Record<string, string>, body: string): MimeTextPart | undefined {
  const contentType = (headers["content-type"] ?? "text/plain").toLowerCase();
  if (contentType.startsWith("multipart/")) {
    const boundary = headers["content-type"]?.match(/boundary="?([^";]+)"?/i)?.[1];
    if (!boundary) {
      return undefined;
    }
    let htmlPart: MimeTextPart | undefined;
    for (const rawPart of splitMimeParts(body, boundary)) {
      const { headers: partHeaders, body: partBody } = splitHeadersAndBody(rawPart);
      if ((partHeaders["content-disposition"] ?? "").toLowerCase().startsWith("attachment")) {
        continue;
      }
      const found = findTextPart(partHeaders, partBody);
      if (found?.type === "text/plain") {
        return found;
      }
      if (found && !htmlPart) {
        htmlPart = found;
      }
    }
    return htmlPart;
  }
  if (contentType.startsWith("text/html")) {
    return { body, headers, type: "text/html" };
  }
  if (contentType.startsWith("text/") || !headers["content-type"]) {
    return { body, headers, type: "text/plain" };
  }
  return undefined;
}

function splitMimeParts(body: string, boundary: string) {
  const parts = body.split(new RegExp(`(?:^|\\r?\\n)--${escapeRegExp(boundary)}(?:--)?(?:[ \\t]*)(?:\\r?\\n|$)`));
  // parts[0] is the preamble; anything after the closing --boundary-- is the epilogue.
  return parts.slice(1).filter((part) => part.trim().length > 0);
}

function decodeTransferEncoding(headers: Record<string, string>, body: string) {
  const encoding = (headers["content-transfer-encoding"] ?? "").toLowerCase().trim();
  const charset = headers["content-type"]?.match(/charset="?([^";]+)"?/i)?.[1];
  if (encoding === "base64") {
    return decodeCharset(Buffer.from(body.replace(/\s+/g, ""), "base64"), charset);
  }
  if (encoding === "quoted-printable") {
    return decodeCharset(decodeQuotedPrintable(body), charset);
  }
  return body;
}

function decodeQuotedPrintable(value: string): Buffer {
  const joined = value.replace(/=\r?\n/g, ""); // soft line breaks
  const bytes: number[] = [];
  for (let index = 0; index < joined.length; index += 1) {
    const hex = joined.slice(index + 1, index + 3);
    if (joined[index] === "=" && /^[0-9A-Fa-f]{2}$/.test(hex)) {
      bytes.push(parseInt(hex, 16));
      index += 2;
    } else {
      bytes.push(joined.charCodeAt(index) & 0xff);
    }
  }
  return Buffer.from(bytes);
}

function decodeCharset(buffer: Buffer, charset?: string) {
  return /^(iso-8859-1|latin1|windows-1252)$/i.test(charset ?? "") ? buffer.toString("latin1") : buffer.toString("utf8");
}

function htmlToText(html: string) {
  return decodeHtmlEntities(
    html
      .replace(/<(style|script|head)[\s\S]*?<\/\1>/gi, "")
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<li[^>]*>/gi, "- ")
      .replace(/<\/(p|div|tr|li|h[1-6]|table|blockquote|ul|ol)>/gi, "\n")
      .replace(/<[^>]+>/g, "")
  )
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function decodeHtmlEntities(value: string) {
  const named: Record<string, string> = { amp: "&", apos: "'", gt: ">", lt: "<", nbsp: " ", quot: '"' };
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec: string) => String.fromCodePoint(Number(dec)))
    .replace(/&([a-z]+);/gi, (match, name: string) => named[name.toLowerCase()] ?? match);
}

function cleanupText(value: string) {
  return value.replace(/\n{3,}/g, "\n\n").trim();
}

function emailAddress(value?: string) {
  return value?.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]?.toLowerCase();
}

// RFC 2047 encoded words in subjects — both B (base64) and Q (quoted-printable) encodings.
function decodeMimeWords(value: string) {
  return value.replace(/=\?([^?]+)\?([bq])\?([^?]*)\?=/gi, (_, charset: string, encoding: string, text: string) => {
    const buffer = encoding.toLowerCase() === "b"
      ? Buffer.from(text, "base64")
      : decodeQuotedPrintable(text.replace(/_/g, " "));
    return decodeCharset(buffer, charset);
  });
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function quote(value: string) {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
