import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { isAutoGeneratedEmail, parseRfc822 } from "../dist/modules/tickets/imap-mailbox.js";

// Tickets store PLAIN TEXT: the importer must pick the text/plain MIME alternative (decoding
// its transfer encoding), fall back to tag-stripped HTML, and never leak raw multipart source
// or boundary noise into the ticket body.

const CRLF = "\r\n";

function message(lines) {
  return lines.join(CRLF);
}

test("multipart/alternative prefers the decoded text/plain part over the HTML part", () => {
  const raw = message([
    "From: Kunde <kunde@example.com>",
    "To: support@dezhost.com",
    "Subject: =?utf-8?q?St=C3=B6rung_Webseite?=",
    'Content-Type: multipart/alternative; boundary="BOUND1"',
    "",
    "--BOUND1",
    'Content-Type: text/plain; charset="utf-8"',
    "Content-Transfer-Encoding: quoted-printable",
    "",
    "Hallo Team,=0Adie Webseite l=C3=A4dt nicht mehr.=0AGr=C3=BC=C3=9Fe",
    "--BOUND1",
    'Content-Type: text/html; charset="utf-8"',
    "",
    "<html><body><p>Hallo Team,</p><p>die Webseite lädt nicht mehr.</p></body></html>",
    "--BOUND1--",
    ""
  ]);

  const parsed = parseRfc822(raw);
  assert.equal(parsed.from, "kunde@example.com");
  assert.equal(parsed.subject, "Störung Webseite");
  assert.match(parsed.body, /die Webseite lädt nicht mehr\./);
  assert.doesNotMatch(parsed.body, /<p>|<html>|BOUND1|Content-Type/i);
});

test("HTML-only mail is converted to readable plain text (tags stripped, entities decoded)", () => {
  const html = "<html><head><style>p{color:red}</style></head><body><h1>Angebot</h1><p>Erste Zeile&nbsp;&amp; mehr</p><ul><li>Punkt eins</li><li>Punkt zwei</li></ul></body></html>";
  const raw = message([
    "From: sender@example.org",
    "To: support@dezhost.com",
    "Subject: Werbung",
    'Content-Type: text/html; charset="utf-8"',
    "Content-Transfer-Encoding: base64",
    "",
    Buffer.from(html, "utf8").toString("base64")
  ]);

  const parsed = parseRfc822(raw);
  assert.match(parsed.body, /Angebot/);
  assert.match(parsed.body, /Erste Zeile & mehr/);
  assert.match(parsed.body, /- Punkt eins\n- Punkt zwei/);
  assert.doesNotMatch(parsed.body, /<|>|color:red/);
});

test("nested multipart (mixed → alternative) still finds the text part and skips attachments", () => {
  const raw = message([
    "From: kunde@example.com",
    "Subject: Anhang",
    'Content-Type: multipart/mixed; boundary="OUTER"',
    "",
    "--OUTER",
    'Content-Type: multipart/alternative; boundary="INNER"',
    "",
    "--INNER",
    "Content-Type: text/plain",
    "",
    "Siehe Anhang.",
    "--INNER",
    "Content-Type: text/html",
    "",
    "<p>Siehe Anhang.</p>",
    "--INNER--",
    "--OUTER",
    "Content-Type: application/pdf",
    'Content-Disposition: attachment; filename="rechnung.pdf"',
    "Content-Transfer-Encoding: base64",
    "",
    "JVBERi0xLjQ=",
    "--OUTER--",
    ""
  ]);

  const parsed = parseRfc822(raw);
  assert.equal(parsed.body, "Siehe Anhang.");
});

test("isAutoGeneratedEmail flags RFC 3834 / bounce / bulk mail, passes human mail", () => {
  assert.equal(isAutoGeneratedEmail({ "auto-submitted": "auto-generated" }), true);
  assert.equal(isAutoGeneratedEmail({ "auto-submitted": "auto-replied" }), true);
  assert.equal(isAutoGeneratedEmail({ "auto-submitted": "no" }), false);
  assert.equal(isAutoGeneratedEmail({ "x-auto-response-suppress": "All" }), true);
  assert.equal(isAutoGeneratedEmail({ precedence: "bulk" }), true);
  assert.equal(isAutoGeneratedEmail({ "content-type": 'multipart/report; report-type="delivery-status"' }), true);
  assert.equal(isAutoGeneratedEmail({ from: "MAILER-DAEMON@mx.example.com" }), true);
  assert.equal(isAutoGeneratedEmail({ from: "kunde@example.com", subject: "Hilfe" }), false);
});

test("mailbox import skips the system's own senders and auto-generated mail", async () => {
  const ticketsService = await readFile(new URL("../src/modules/tickets/tickets.service.ts", import.meta.url), "utf8");
  // Own outbound identities + own inbox addresses are collected once per run…
  assert.match(ticketsService, /systemSenderAddresses\(\)/);
  assert.match(ticketsService, /configs\.map\(\(config\) => config\.address\.trim\(\)\.toLowerCase\(\)\)/);
  // …and every message from them (or flagged machine-generated) is logged as SKIPPED_SYSTEM.
  assert.match(ticketsService, /systemAddresses\.has\(sender\) \|\| isAutoGeneratedEmail\(message\.headers\)/);
  assert.match(ticketsService, /SKIPPED_SYSTEM/);
});

test("outbound system mail is stamped machine-generated so it can never loop back as a ticket", async () => {
  const emailService = await readFile(new URL("../src/modules/email/email.service.ts", import.meta.url), "utf8");
  assert.match(emailService, /"Auto-Submitted: auto-generated"/);
  assert.match(emailService, /"X-Auto-Response-Suppress: All"/);
});

test("ticket delete is exposed admin-only and cascades in the schema", async () => {
  const controller = await readFile(new URL("../src/modules/tickets/tickets.controller.ts", import.meta.url), "utf8");
  const schema = await readFile(new URL("../../../prisma/schema.prisma", import.meta.url), "utf8");

  assert.match(controller, /@Delete\(":id"\)\s*\n\s*@Roles\("admin", "super_admin"\)/);
  // Replies/notes/attachments cascade with the ticket row.
  assert.match(schema, /model TicketReply[\s\S]*?ticket\s+Ticket\s+@relation\(fields: \[ticketId\], references: \[id\], onDelete: Cascade\)/);
  assert.match(schema, /model TicketAttachment[\s\S]*?ticket\s+Ticket\s+@relation\(fields: \[ticketId\], references: \[id\], onDelete: Cascade\)/);
});
